name: Create Discussion
on:
  workflow_dispatch:
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            mutation($title:String!, $body:String!) {
              createDiscussion(input: {repositoryId: "R_kgDOI5vcDQ", categoryId: "DIC_kwDOI5vcDc4CUA42", title: "test", body: "body"}) {
                discussion {
                  id
                }
              }
            }
          owner: "toyamarinyon"
          repo: "raula"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
